# Runs ruff, black in main branch and merge_requests
stages:
  - validate

# Black sub-stage in the validate stage
cq-black:
  stage: validate
  image: pyfound/black:latest_release
  script:
    - black --diff --color --line-length 119 .
    - black --check --verbose --line-length 119 .
  only:
    refs:
      - merge_requests
      - main

# Ruff sub-stage in the validate stage
cq-ruff:
  stage: validate
  image: ghcr.io/astral-sh/ruff:latest
  script:
    - ls .
    - ruff check . --output-format gitlab > gl-code-quality-report.json
  only:
    refs:
      - merge_requests
      - main
  artifacts:
    name: "${CI_PROJECT_NAME}_code_quality"
    when: always
    reports:
      codequality: gl-code-quality-report.json
