# Runs pylama, black in main, merge_requests
stages:
  - code-quality

# Black sub-stage in the code-quality stage
black:
  stage: code-quality
  image: detecttechnologies/python-code-quality:latest
  script:
    - black --diff --color --line-length 119 .
    - black --check --line-length 119 .
  only:
    refs:
      - merge_requests
      - main

# Ruff sub-stage in the code-quality stage
ruff:
  stage: code-quality
  image: "python:3.10"
  before_script:
    - 'pip3 install ruff'
  script:
    - ls .
    - ruff check . --format gitlab > gl-code-quality-report.json
  only:
    refs:
      - merge_requests
      - main
  artifacts:
    name: "${CI_PROJECT_NAME}_code_quality"
    when: always
    reports:
      codequality: gl-code-quality-report.json
