copy-to-central-git:
  stage: push
  image: python
  script:
    - bash -c "$(curl -fsSL https://github.com/avinashtrivedi11/Gitlab-CI-CD-Templates/raw/python-solution/knowledge-portal/source/initiate-push-to-central.sh)"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
