copy-to-central-git:
  stage: push
  image: bitnami/git
  script:
    - |
      # Extract the path to the manifest file and the source-repo's path
      arrIN=(${CI_REPOSITORY_URL//"DetectTechnologies/"/ })   # split repo path after DetectTechnologies
      arrIN1=(${arrIN[1]//"."/ })                             # split repo path before .git
      source_repo_path=${arrIN1[0]}
      manifest_path=${source_repo_path//"/"/_}
      echo "Done, source-repo's path: ${source_repo_path}, manifest path: ${manifest_path}"

    - |
      # Clone the destination repo, copy the source-git's manifest to central-git by adding source-path in manifest filename
      git clone $CENTRAL_GIT_PUSH_URL /root/dest
      mkdir -p /root/dest/manifests
      cp -v docs-manifest.txt /root/dest/manifests/docs-manifest_${manifest_path}.txt
      echo "Done"

    - |
      # Read every line of the manifest file, and copy it over with the required central-git mapping
      cat docs-manifest.txt | while read line
      do
        if [[ "$line" == *"-->"* ]];
          then
            split=(${line//-->/ });
            source=${split[0]};
            destination=${split[1]};
            if [[ "$destination" == *"/"* ]];
            then
              path="${destination%/*}"
              file="${destination##*/}";
              mkdir -p /root/dest/${path}   # Ensure the destination folder exists at central-git
              cp -R -v ${source} /root/dest/${path}/${file};    # Copy the source file to the required prefix at central-git
            fi
        fi
      done
      echo "Done"

    - |
      # Push back to central-git with the updated changes
      cd /root/dest
      git config --global user.email "PlatformTeam@detecttechnologies.com"
      git config --global user.name "Detect Gitlab Bot"
      git add -A && git commit -m "Commit in source pipeline for ${source_repo_path}" --allow-empty;
      git push origin HEAD:main -f;
      echo "Done"

  only:
    refs:
      - main