# Predefined templates for code quality and security checks
include:
  - template: Jobs/Code-Quality.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

# Define the sequence of pipeline stages
stages:
  - generate
  - test

# Generate frontend pipeline configuration
frontend_pipeline_generator:
  stage: generate
  image: registry.gitlab.com/detecttechnologies/software/webapps/t-pulse/web/tpulse-msa/tpulse-msa-cicd/tpulse-python:1.0
  variables:
    DOCKER_AUTH_CONFIG: '{"auths":{"registry.gitlab.com":{"username":"${CONTAINER_REGISTRY_USER}","password":"${CONTAINER_REGISTRY_TOKEN}"}}}'
  script:
    - cp -R /app/scripts/* ./
    - python3 frontend_pipeline_generator.py
  artifacts:
    paths:
      - frontend_pipeline.yml
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"

# Trigger the pipeline using the generated configuration
frontend_pipeline_trigger:
  stage: generate
  needs: ["frontend_pipeline_generator"]
  trigger:
    include:
      - artifact: frontend_pipeline.yml
        job: frontend_pipeline_generator
    strategy: depend
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
  
# Code quality checks; primarily triggered on merge requests
code_quality:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "pipeline"  
      when: never 
    - when: never

# Detect any exposed secrets in the code; primarily triggered on merge requests
secret_detection:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "pipeline"  
    - when: never

# Static security analysis for Node.js; primarily triggered on merge requests
nodejs-scan-sast:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "pipeline"  
    - when: never

# Static security analysis using Semgrep; primarily triggered on merge requests
semgrep-sast:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "pipeline"  
    - when: never
