# Include Gitlab template Jobs
include:
  - template: Jobs/Code-Quality.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

# Define pipeline stages
stages:
  - build
  - test
  - deploy

default:
  tags:
    - saas-linux-medium-amd64

# Build Stage
# Get node_modules
install_dependencies:
  image: registry.gitlab.com/detecttechnologies/software/webapps/t-pulse/web/tpulse-msa/tpulse-msa-cicd/tpulse-nodejs:1.0
  stage: build
  variables:
    DOCKER_AUTH_CONFIG: '{"auths":{"registry.gitlab.com":{"username":"${CONTAINER_REGISTRY_USER}","password":"${CONTAINER_REGISTRY_TOKEN}"}}}'
  script:
    - npm ci
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "pipeline"

build_dist:
  stage: build
  needs: ["install_dependencies"]
  image: registry.gitlab.com/detecttechnologies/software/webapps/t-pulse/web/tpulse-msa/tpulse-msa-cicd/tpulse-nodejs:1.0
  variables:
    DOCKER_AUTH_CONFIG: '{"auths":{"registry.gitlab.com":{"username":"${CONTAINER_REGISTRY_USER}","password":"${CONTAINER_REGISTRY_TOKEN}"}}}'
  before_script:
    - apt-get update && apt-get install -y git bash
  script:
    - npm run build
  artifacts:
    paths:
      - $CI_PROJECT_DIR/dist
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pull
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "pipeline"


# # NG lint job in test stage
# ng_lint:
#   stage: test
#   image: registry.gitlab.com/detecttechnologies/software/webapps/t-pulse/web/tpulse-msa/tpulse-msa-cicd/tpulse-nodejs:1.0
#   variables:
#     DOCKER_AUTH_CONFIG: '{"auths":{"registry.gitlab.com":{"username":"${CONTAINER_REGISTRY_USER}","password":"${CONTAINER_REGISTRY_TOKEN}"}}}'
#   script:
#     - npm i -g @angular/cli@13.3.10
#     - ng add @angular-eslint/schematics --skip-confirmation
#     - cat package.json
#     - cat .eslintrc.json
#     - ng lint || true
#   cache:
#     key:
#       files:
#         - package-lock.json
#     paths:
#       - node_modules
#     policy: pull
#   rules:
#     - if: $CI_PIPELINE_SOURCE == "merge_request_event"
#     - if: $CI_PIPELINE_SOURCE == "pipeline"

code_quality:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "pipeline"

nodejs-scan-sast:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "pipeline"

secret_detection:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "pipeline"

semgrep-sast:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "pipeline"


# Deploy Jobs
# Deploys to EC2 VM


deploy_dist:
  stage: deploy
  image: registry.gitlab.com/detecttechnologies/software/webapps/t-pulse/web/tpulse-msa/tpulse-msa-cicd/tpulse-python:1.0
  variables:
    TZ: "Asia/Kolkata"
  variables:
    DOCKER_AUTH_CONFIG: '{"auths":{"registry.gitlab.com":{"username":"${CONTAINER_REGISTRY_USER}","password":"${CONTAINER_REGISTRY_TOKEN}"}}}'
  environment:
    name: $ENVIRONMENT
  script:
    - cp -R /app/scripts/* ./
    ## Sync time with NTP server
    - service chrony start
    - chronyc -a 'burst 4/4' && sleep 10
    - chronyc sources
    ## Connect to VPN
    - python3 connect_vpn.py
    - sleep 20s
    - cat client.log
    - echo "nameserver 8.8.8.8" >> /etc/resolv.conf
    - IP_ADDRESS=$(curl ifconfig.me)
    - echo "Public IP Address:$IP_ADDRESS"
    ## Deploy to EC2 VM
    - bash deploy_dist.sh
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
    - when: never